update_notifier.settings:
  type: config_object
  label: 'Update Notifier settings'
  mapping:
    notify:
     type: mapping
     label: 'Notify user'
     mapping:
       price_change:
         type: boolean
         label: 'Notify user when product price changes'
       on_sale:
         type: boolean
         label: 'Notify user when product goes on sale'
       promotion:
         type: boolean
         label: 'Notify user when product has promotion'
       in_stock:
         type: boolean
         label: 'Notify user when product is in stock'
