update_notifier.settings:
  type: config_object
  mapping:
    price_change:
      type: string
      label: 'Message sent when product price changes'
    on_sale:
      type: string
      label: 'Message sent when product goes on sale'
    promotion:
      type: string
      label: 'Message sent when product has promotion'
    in_stock:
      type: string
      label: 'Message sent when product is in stock'
    email_message:
      type: string
      label: 'Email message sent when product changes.'
