<?php

/**
 * @file
 * Contains follow.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function follow_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the follow module.
    case 'help.page.follow':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allow user to be followed') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function follow_theme() {
  return [
    'follow' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_user_login().
 */
function follow_user_login($account) {
  $config = \Drupal::config('follow.adminsettings');
  drupal_set_message($config->get('welcome_message'));
}
