<?php

/**
 * @file
 * DIBA carousel Module.
 */

use Drupal\Core\Database\Query\SelectInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function diba_carousel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.diba_carousel':
      return t('Diba carouse block based on Bootstrap carousel.');
  }
}

/**
 * Implements hook_theme().
 */
function diba_carousel_theme($existing, $type, $theme, $path) {
  return [
    'block__diba_carousel' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_query_TAG_alter().
 */
function diba_carousel_query_random_order_alter(SelectInterface $query) {
  // Select a random element.
  $query->orderRandom();
}
